
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu May 23 09:21:23 CEST 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRINGA = 8;
  public static final int DUE = 16;
  public static final int U = 10;
  public static final int USER = 9;
  public static final int OPERAZIONE = 4;
  public static final int INDIRIZZO = 7;
  public static final int DATA = 2;
  public static final int SEZIONE = 6;
  public static final int LOGIN = 12;
  public static final int EOF = 0;
  public static final int ZERO = 14;
  public static final int SEP = 13;
  public static final int error = 1;
  public static final int ORA = 3;
  public static final int UNO = 15;
  public static final int LOGOUT = 11;
  public static final int CLASSE = 5;
}

